#!/usr/bin/env python3

import argparse
import os

import google_compute_engine

parser = argparse.ArgumentParser(
    description="Describe the bentoml bundle on Google Compute Engine",
    epilog="Check out https://github.com/bentoml/google-compute-engine-deploy#readme to know more",
)
parser.add_argument(
    "deployment_name", help="The name you used for your deployment"
)
parser.add_argument(
    "config_json",
    help="The config file for your deployment",
    default=os.path.join(os.getcwd(), "cloud_engine_config.json"),
    nargs="?",
)
args = parser.parse_args()

deployment_spec = google_compute_engine.get_configuration_value(args.config_json)
print(google_compute_engine.describe(args.deployment_name, deployment_spec))
